import { useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api, asList, queryString } from '../lib/api'
import { currentMonth, formatMoney, monthLabel } from '../lib/format'
import type { Category, ListResponse } from '../lib/types'
import { Badge, ErrorState, PageHeader, State } from '../components/ui'

interface CategoryDetail { category_id: string | number; forecast_minor: number }
interface Month { month: string; income: number; expense: number; c_end: number; r_end: number; f_end: number; category_details?: CategoryDetail[] }
interface Forecast { months: Month[] }
const colors = ['#557a5d', '#d87961', '#c49a51', '#617c9c', '#987ca1', '#6f9b91', '#b66868']
function minusMonths(month: string, amount: number) { const [y,m] = month.split('-').map(Number); const d = new Date(y,m-1-amount,1); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}` }

export function AnalyticsPage() {
  const [end, setEnd] = useState(currentMonth()); const [period, setPeriod] = useState<6|12|24>(12)
  const start = minusMonths(end, period - 1)
  const report = useQuery<Forecast>({ queryKey: ['analytics', start, period], queryFn: () => api(`/forecast?${queryString({ from_month: start, months: period, include_possible: false })}`) })
  const categoryQuery = useQuery<Category[] | ListResponse<Category>>({ queryKey: ['categories', 'all'], queryFn: () => api('/categories?include_archived=true') })
  const timeline = report.data?.months.map((m) => ({ ...m, label: monthLabel(m.month, true), incomeRub: m.income/100, expenseRub: m.expense/100, freeRub: m.f_end/100, reserveRub: m.r_end/100 })) ?? []
  const categories = useMemo(() => { const names = new Map(asList(categoryQuery.data).map((category) => [String(category.id), category.name])); const map = new Map<string, number>(); report.data?.months.forEach((m) => m.category_details?.forEach((c) => { const key = names.get(String(c.category_id)) ?? `Категория #${c.category_id}`; map.set(key, (map.get(key) ?? 0) + c.forecast_minor) })); return [...map].map(([name, value]) => ({ name, value: value/100 })).sort((a,b) => b.value-a.value).slice(0,8) }, [report.data, categoryQuery.data])
  return <div className="page"><PageHeader eyebrow="Отчёты" title="Аналитика" description="Плановая динамика денег, резервов и потребительских расходов." actions={<div className="toolbar"><input className="input" type="month" value={end} onChange={(e) => setEnd(e.target.value)}/><select className="input" value={period} onChange={(e) => setPeriod(Number(e.target.value) as 6|12|24)}><option value="6">6 месяцев</option><option value="12">12 месяцев</option><option value="24">24 месяца</option></select></div>}/>
    <div className="plan-options"><Badge tone="neutral">Переводы и выделение резервов исключены из потребительских расходов</Badge></div>
    {report.isLoading && <State kind="loading" title="Готовим аналитику"/>}{report.isError && <ErrorState error={report.error} retry={() => report.refetch()}/>} {report.data && <><div className="chart-card"><div className="section-head"><div><span className="eyebrow">Движение</span><h2>Доходы и расходы</h2></div></div><ResponsiveContainer width="100%" height={320}><BarChart data={timeline} margin={{ top: 12, right: 12, left: 0, bottom: 0 }}><CartesianGrid vertical={false} stroke="var(--chart-grid)"/><XAxis dataKey="label" tickLine={false} axisLine={false}/><YAxis tickFormatter={(v) => `${Math.round(v/1000)} тыс.`} tickLine={false} axisLine={false} width={65}/><Tooltip formatter={(value) => formatMoney(Number(value)*100)} labelFormatter={(label) => String(label)}/><Legend/><Bar dataKey="incomeRub" name="Доходы" fill="var(--green)" radius={[5,5,0,0]}/><Bar dataKey="expenseRub" name="Расходы" fill="var(--coral)" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div><div className="chart-grid"><div className="chart-card"><div className="section-head"><div><span className="eyebrow">Структура</span><h2>По категориям</h2></div></div>{categories.length ? <div className="pie-layout"><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={categories} dataKey="value" nameKey="name" innerRadius={62} outerRadius={100} paddingAngle={2}>{categories.map((_,i) => <Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={(v) => formatMoney(Number(v)*100)}/></PieChart></ResponsiveContainer><div className="chart-legend">{categories.map((c,i) => <div key={c.name}><i style={{background: colors[i%colors.length]}}/><span>{c.name}</span><b>{formatMoney(c.value*100)}</b></div>)}</div></div> : <State title="Недостаточно данных"/>}</div><div className="chart-card"><div className="section-head"><div><span className="eyebrow">Остатки</span><h2>Свободно и в резервах</h2></div></div><ResponsiveContainer width="100%" height={300}><LineChart data={timeline}><CartesianGrid vertical={false} stroke="var(--chart-grid)"/><XAxis dataKey="label" tickLine={false} axisLine={false}/><YAxis tickFormatter={(v) => `${Math.round(v/1000)} тыс.`} tickLine={false} axisLine={false} width={65}/><Tooltip formatter={(v) => formatMoney(Number(v)*100)}/><Legend/><Line type="monotone" dataKey="freeRub" name="Свободно" stroke="var(--green)" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="reserveRub" name="В резервах" stroke="var(--blue)" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></div></div></>}
  </div>
}
